"""
https://leetcode.com/problems/find-the-difference/
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
"""

# Pretty easy.
# time complexity: O(n+m), space complexity: O(n), where n is the length of string s, m is the length of string t
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        s = list(s)
        for i in t:
            if i in s:
                s.remove(i)
            else:
                return i
